fragment Hero on Hero {
    ...HeroBase
    ntVariantsCollection(limit: 8) {
        items {
            ...HeroBase
            ntAudience {
                ...Audience
            }
        }
    }
}

fragment HeroBase on Hero {
    ...ContentfulEntry
    headline {
        json
        links {
            entries {
                inline {
                    ...ContentfulEntry
                    ... on NtMergetag {
                        ...ContentfulEntry
                        id
                    }
                }
            }
        }
    }
    subline {
        json
    }
    image {
        url
    }
}